/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_guobi_gbime_engine_GBIMEEngineV52 */

#ifndef _Included_GBIMEEngineV52
#define _Included_GBIMEEngineV52
#ifdef __cplusplus
extern "C" {
#endif


//#define NEED_PRINT_METHOD	1
//#define JNI_DEBUG
#ifdef JNI_DEBUG
	#ifdef WIN32
	#include <E:\Android\android-ndk-r7\platforms\android-9\arch-x86\usr\include\android\log.h>
	#else
		#include "android/log.h"
	#endif
	#define LOG_TAG    "JNI_LOG" // 这个是自定义的LOG的标识，可用来定位
	#undef LOG // 取消默认的LOG
	#define LOGD(...)  __android_log_print(ANDROID_LOG_DEBUG,LOG_TAG,__VA_ARGS__) // 定义LOG类型
	#define LOGI(...)  __android_log_print(ANDROID_LOG_INFO,LOG_TAG,__VA_ARGS__) // 定义LOG类型
	#define LOGW(...)  __android_log_print(ANDROID_LOG_WARN,LOG_TAG,__VA_ARGS__) // 定义LOG类型
	#define LOGE(...)  __android_log_print(ANDROID_LOG_ERROR,LOG_TAG,__VA_ARGS__) // 定义LOG类型
	#define LOGF(...)  __android_log_print(ANDROID_LOG_FATAL,LOG_TAG,__VA_ARGS__) // 定义LOG类型

	#define PRINT_METHOD(method) \
		{ \
		if(NEED_PRINT_METHOD > 0) \
			LOGD("jni:"method); \
		}


#else
	#define LOGD(...)	;
	#define LOGI(...)	;
	#define LOGW(...)	;
	#define LOGE(...)	;
	#define LOGF(...)	;

	#define PRINT_METHOD(method)	;
#endif


/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    newInstance
 * Signature: ()J
 */
extern jlong Java_com_guobi_gbime_engine_GBIMEEngineV52_newInstance
  (JNIEnv *, jclass);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    deleteInstance
 * Signature: (J)V
 */
extern void Java_com_guobi_gbime_engine_GBIMEEngineV52_deleteInstance
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    open
 * Signature: (J[B)I
 */
extern jint Java_com_guobi_gbime_engine_GBIMEEngineV52_open
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    openEx
 * Signature: (J[B[B)I
 */
extern jint Java_com_guobi_gbime_engine_GBIMEEngineV52_openEx
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    openWithUDB
 * Signature: (J[B[BI)I
 */
extern jint Java_com_guobi_gbime_engine_GBIMEEngineV52_openWithUDB
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    openExWithUDB
 * Signature: (J[B[BI[B[BI)I
 */
extern jint Java_com_guobi_gbime_engine_GBIMEEngineV52_openExWithUDB
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    close
 * Signature: (J)V
 */
extern void Java_com_guobi_gbime_engine_GBIMEEngineV52_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    isOpened
 * Signature: (J)Z
 */
extern jboolean Java_com_guobi_gbime_engine_GBIMEEngineV52_isOpened
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    enableUpdateCallback
 * Signature: (JZ)V
 */
extern void Java_com_guobi_gbime_engine_GBIMEEngineV52_enableUpdateCallback
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    setUDBUpdateCallbackFreq
 * Signature: (JI)I
 */
extern jint Java_com_guobi_gbime_engine_GBIMEEngineV52_setUDBUpdateCallbackFreq
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    clearAllUDBData
 * Signature: (J)V
 */
extern void Java_com_guobi_gbime_engine_GBIMEEngineV52_clearAllUDBData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    deleteUDBPhrase
 * Signature: (JLjava/lang/String;)I
 */
extern jint Java_com_guobi_gbime_engine_GBIMEEngineV52_deleteUDBPhrase
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    startEnumerateUDBPhrase
 * Signature: (J)V
 */
extern void Java_com_guobi_gbime_engine_GBIMEEngineV52_startEnumerateUDBPhrase
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    enumerateNextUDBPhrase
 * Signature: (J)Ljava/lang/String;
 */
extern jstring Java_com_guobi_gbime_engine_GBIMEEngineV52_enumerateNextUDBPhrase
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    enablePagingCallback
 * Signature: (JZ)V
 */
extern void Java_com_guobi_gbime_engine_GBIMEEngineV52_enablePagingCallback
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    setAlpPagingOptions
 * Signature: (JIII)I
 */
extern jint Java_com_guobi_gbime_engine_GBIMEEngineV52_setAlpPagingOptions
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    setChnPagingOptions
 * Signature: (JIII)I
 */
extern jint Java_com_guobi_gbime_engine_GBIMEEngineV52_setChnPagingOptions
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    setSyllPagingOptions
 * Signature: (JIII)I
 */
extern jint Java_com_guobi_gbime_engine_GBIMEEngineV52_setSyllPagingOptions
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    setInputMode
 * Signature: (JII)I
 */
extern jint Java_com_guobi_gbime_engine_GBIMEEngineV52_setInputMode
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    inputEvent
 * Signature: (JI)I
 */
extern jint Java_com_guobi_gbime_engine_GBIMEEngineV52_inputEvent
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    inputEventEx
 * Signature: (JIJ)I
 */
extern jint Java_com_guobi_gbime_engine_GBIMEEngineV52_inputEventEx
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    inputDefaultInterpuction
 * Signature: (J)I
 */
extern jint Java_com_guobi_gbime_engine_GBIMEEngineV52_inputDefaultInterpuction
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    clearAllInput
 * Signature: (J)V
 */
extern void Java_com_guobi_gbime_engine_GBIMEEngineV52_clearAllInput
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    hasCandidate
 * Signature: (J)Z
 */
extern jboolean Java_com_guobi_gbime_engine_GBIMEEngineV52_hasCandidate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    getCandCountInPage
 * Signature: (J)I
 */
extern jint Java_com_guobi_gbime_engine_GBIMEEngineV52_getCandCountInPage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    hasPrevCandPage
 * Signature: (J)Z
 */
extern jboolean Java_com_guobi_gbime_engine_GBIMEEngineV52_hasPrevCandPage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    hasNextCandPage
 * Signature: (J)Z
 */
extern jboolean Java_com_guobi_gbime_engine_GBIMEEngineV52_hasNextCandPage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    movePrevCandPage
 * Signature: (J)Z
 */
extern jboolean Java_com_guobi_gbime_engine_GBIMEEngineV52_movePrevCandPage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    moveNextCandPage
 * Signature: (J)Z
 */
extern jboolean Java_com_guobi_gbime_engine_GBIMEEngineV52_moveNextCandPage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    getCandInPageByIdx
 * Signature: (JI)Ljava/lang/String;
 */
extern jstring Java_com_guobi_gbime_engine_GBIMEEngineV52_getCandInPageByIdx
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    getCandInputLenInPageByIdx
 * Signature: (JI)I
 */
extern jint Java_com_guobi_gbime_engine_GBIMEEngineV52_getCandInputLenInPageByIdx
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    selectCandInPageByIdx
 * Signature: (JI)V
 */
extern void Java_com_guobi_gbime_engine_GBIMEEngineV52_selectCandInPageByIdx
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    hasSyllable
 * Signature: (J)Z
 */
extern jboolean Java_com_guobi_gbime_engine_GBIMEEngineV52_hasSyllable
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    getSyllCountInPage
 * Signature: (J)I
 */
extern jint Java_com_guobi_gbime_engine_GBIMEEngineV52_getSyllCountInPage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    hasPrevSyllPage
 * Signature: (J)Z
 */
extern jboolean Java_com_guobi_gbime_engine_GBIMEEngineV52_hasPrevSyllPage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    hasNextSyllPage
 * Signature: (J)Z
 */
extern jboolean Java_com_guobi_gbime_engine_GBIMEEngineV52_hasNextSyllPage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    movePrevSyllPage
 * Signature: (J)Z
 */
extern jboolean Java_com_guobi_gbime_engine_GBIMEEngineV52_movePrevSyllPage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    moveNextSyllPage
 * Signature: (J)Z
 */
extern jboolean Java_com_guobi_gbime_engine_GBIMEEngineV52_moveNextSyllPage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    getSyllInPageByIdx
 * Signature: (JI)Ljava/lang/String;
 */
extern jstring Java_com_guobi_gbime_engine_GBIMEEngineV52_getSyllInPageByIdx
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    selectSyllInPageByIdx
 * Signature: (JI)V
 */
extern void Java_com_guobi_gbime_engine_GBIMEEngineV52_selectSyllInPageByIdx
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    getSelectedSyllIdx
 * Signature: (J)I
 */
extern jint Java_com_guobi_gbime_engine_GBIMEEngineV52_getSelectedSyllIdx
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    getInputString
 * Signature: (J)Ljava/lang/String;
 */
extern jstring Java_com_guobi_gbime_engine_GBIMEEngineV52_getInputString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    getOutputString
 * Signature: (J)Ljava/lang/String;
 */
extern jstring Java_com_guobi_gbime_engine_GBIMEEngineV52_getOutputString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    getUpScreenString
 * Signature: (J)Ljava/lang/String;
 */
extern jstring Java_com_guobi_gbime_engine_GBIMEEngineV52_getUpScreenString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    clearUpScreenString
 * Signature: (J)V
 */
extern void Java_com_guobi_gbime_engine_GBIMEEngineV52_clearUpScreenString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    getStorkeString
 * Signature: (J)Ljava/lang/String;
 */
extern jstring Java_com_guobi_gbime_engine_GBIMEEngineV52_getStorkeString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    getComponentsCount
 * Signature: (J)I
 */
extern jint Java_com_guobi_gbime_engine_GBIMEEngineV52_getComponentsCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    getComponentStringByIdx
 * Signature: (JI)Ljava/lang/String;
 */
extern jstring Java_com_guobi_gbime_engine_GBIMEEngineV52_getComponentStringByIdx
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    getComponentUnicodeByIdx
 * Signature: (JI)I
 */
extern jint Java_com_guobi_gbime_engine_GBIMEEngineV52_getComponentUnicodeByIdx
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    setAssocWord
 * Signature: (JLjava/lang/String;Z)I
 */
extern jint Java_com_guobi_gbime_engine_GBIMEEngineV52_setAssocWord
  (JNIEnv *, jclass, jlong, jstring, jboolean);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    setCapState
 * Signature: (JIIZ)I
 */
extern jint Java_com_guobi_gbime_engine_GBIMEEngineV52_setCapState
  (JNIEnv *, jclass, jlong, jint, jint, jboolean);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    setFuzzyOptions
 * Signature: (JJZ)I
 */
extern jint Java_com_guobi_gbime_engine_GBIMEEngineV52_setFuzzyOptions
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    switchToSlaveLang
 * Signature: (JI)I
 */
extern jint Java_com_guobi_gbime_engine_GBIMEEngineV52_switchToSlaveLang
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    setEngineOption
 * Signature: (JIJJ)I
 */
extern jint Java_com_guobi_gbime_engine_GBIMEEngineV52_setEngineOption
  (JNIEnv *, jclass, jlong, jint, jlong, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    getCurState
 * Signature: (J)I
 */
extern jint Java_com_guobi_gbime_engine_GBIMEEngineV52_getCurState
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    enableLog
 * Signature: (JZ)V
 */
extern void Java_com_guobi_gbime_engine_GBIMEEngineV52_enableLog
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    registerInterpunctionKeyEx
 * Signature: (JILjava/lang/String;IIIII)I
 */
extern jint Java_com_guobi_gbime_engine_GBIMEEngineV52_registerInterpunctionKeyEx
  (JNIEnv *, jclass, jlong, jint, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    selectCandEx
 * Signature: (JLjava/lang/String;I)I
 */
extern jint Java_com_guobi_gbime_engine_GBIMEEngineV52_selectCandEx
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    addUDBPhrase
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
extern jint Java_com_guobi_gbime_engine_GBIMEEngineV52_addUDBPhrase
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    getPinyinCode
 * Signature: (JLjava/lang/String;I)Ljava/lang/String;
 */
extern jstring Java_com_guobi_gbime_engine_GBIMEEngineV52_getPinyinCode
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    rewindCandPage
 * Signature: (J)V
 */
extern void Java_com_guobi_gbime_engine_GBIMEEngineV52_rewindCandPage
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
