/* DO NOT EDIT THIS FILE - it is machine generated */


/* Header for class com_guobi_gbime_engine_GBIMEEngineV52 */
#include "com_guobi_gbime_engine_GBIMEEngineV52.h"
#include "GBIMEEngineV52.h"

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    a
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_a
(JNIEnv *env, jclass cls){
	PRINT_METHOD("newInstance");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_newInstance
(env, cls);
}

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    b
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_b
(JNIEnv *env, jclass cls, jlong handle){
	PRINT_METHOD("deleteInstance");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_deleteInstance
(env, cls, handle);
}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    c
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_c
(JNIEnv *env, jclass cls, jlong handle, jbyteArray ldb){
	PRINT_METHOD("open");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_open
(env, cls, handle, ldb);
}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    d
 * Signature: (J[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_d
  (JNIEnv *env, jclass cls, jlong handle, jbyteArray master_ldb, jbyteArray slave_ldb){
	PRINT_METHOD("openEx");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_openEx
  (env, cls, handle, master_ldb, slave_ldb);
}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    aa
 * Signature: (J[B[BI)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_aa
  (JNIEnv *env, jclass cls, jlong handle, jbyteArray ldb, jbyteArray udb, jint udb_size ){
	PRINT_METHOD("openWithUDB");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_openWithUDB
  (env, cls, handle, ldb, udb, udb_size );
}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    ab
 * Signature: (J[B[BI[B[BI)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_ab
(JNIEnv *env, jclass cls, jlong handle, jbyteArray master_ldb,  jbyteArray master_udb, jint master_udb_size, jbyteArray slave_ldb, jbyteArray slave_udb, jint slave_udb_size ){
	PRINT_METHOD("openExWithUDB");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_openExWithUDB
(env, cls, handle, master_ldb, master_udb, master_udb_size, slave_ldb, slave_udb, slave_udb_size );

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    ac
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_ac
  (JNIEnv *env, jclass cls, jlong handle){
	PRINT_METHOD("close");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_close
  (env, cls, handle);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    ad
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_ad
  (JNIEnv *env, jclass cls, jlong handle){
	PRINT_METHOD("isOpened");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_isOpened
  (env, cls, handle);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    ba
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_ba
  (JNIEnv *env, jclass cls, jlong handle, jboolean enable){
	PRINT_METHOD("enableUpdateCallback");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_enableUpdateCallback
  (env, cls, handle, enable);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bb
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bb
  (JNIEnv *env, jclass cls, jlong handle, jint update_freq){
	PRINT_METHOD("setUDBUpdateCallbackFreq");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_setUDBUpdateCallbackFreq
  (env, cls, handle, update_freq);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bc
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bc
  (JNIEnv *env, jclass cls, jlong handle){
	PRINT_METHOD("clearAllUDBData");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_clearAllUDBData
  (env, cls, handle);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bd
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bd
  (JNIEnv *env, jclass cls, jlong handle, jstring str){
	PRINT_METHOD("deleteUDBPhrase");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_deleteUDBPhrase
  (env, cls, handle, str);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    ca
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_ca
  (JNIEnv *env, jclass cls, jlong handle){
	PRINT_METHOD("startEnumerateUDBPhrase");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_startEnumerateUDBPhrase
  (env, cls, handle);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    cb
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_cb
  (JNIEnv *env, jclass cls, jlong handle){
	PRINT_METHOD("enumerateNextUDBPhrase");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_enumerateNextUDBPhrase
  (env, cls, handle);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    cc
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_cc
  (JNIEnv *env, jclass cls, jlong handle, jboolean enable){
	PRINT_METHOD("enablePagingCallback");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_enablePagingCallback
  (env, cls, handle, enable);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    cd
 * Signature: (JIII)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_cd
  (JNIEnv *env, jclass cls, jlong handle, jint page_width, jint word_space, jint max_cand){
	PRINT_METHOD("setAlpPagingOptions");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_setAlpPagingOptions
  (env, cls, handle, page_width, word_space, max_cand);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    da
 * Signature: (JIII)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_da
  (JNIEnv *env, jclass cls, jlong handle, jint page_width, jint word_space, jint max_cand){
	PRINT_METHOD("setChnPagingOptions");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_setChnPagingOptions
  (env, cls, handle, page_width, word_space, max_cand);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    db
 * Signature: (JIII)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_db
  (JNIEnv *env, jclass cls, jlong handle, jint page_width, jint word_space, jint max_cand){
	PRINT_METHOD("setSyllPagingOptions");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_setSyllPagingOptions
  (env, cls, handle, page_width, word_space, max_cand);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    dc
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_dc
  (JNIEnv *env, jclass cls, jlong handle, jint input_mode, jint cand_type){
	PRINT_METHOD("setInputMode");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_setInputMode
  (env, cls, handle, input_mode, cand_type);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    dd
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_dd
  (JNIEnv *env, jclass cls, jlong handle, jint evt){
	PRINT_METHOD("inputEvent");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_inputEvent
  (env, cls, handle, evt);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    aaa
 * Signature: (JIJ)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_aaa
  (JNIEnv *env, jclass cls, jlong handle, jint evt, jlong param){
	PRINT_METHOD("inputEventEx");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_inputEventEx
  (env, cls, handle, evt, param);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    aab
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_aab
  (JNIEnv *env, jclass cls, jlong handle){
	PRINT_METHOD("inputDefaultInterpuction");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_inputDefaultInterpuction
  (env, cls, handle);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    aac
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_aac
  (JNIEnv *env, jclass cls, jlong handle){
	PRINT_METHOD("clearAllInput");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_clearAllInput
  (env, cls, handle);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    aad
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_aad
  (JNIEnv *env, jclass cls, jlong handle){
	PRINT_METHOD("hasCandidate");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_hasCandidate
  (env, cls, handle);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    aba
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_aba
  (JNIEnv *env, jclass cls, jlong handle){
	PRINT_METHOD("getCandCountInPage");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_getCandCountInPage
  (env, cls, handle);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    abb
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_abb
  (JNIEnv *env, jclass cls, jlong handle){
	PRINT_METHOD("hasPrevCandPage");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_hasPrevCandPage
  (env, cls, handle);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    abc
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_abc
  (JNIEnv *env, jclass cls, jlong handle){
	PRINT_METHOD("hasNextCandPage");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_hasNextCandPage
  (env, cls, handle);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    abd
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_abd
  (JNIEnv *env, jclass cls, jlong handle){
	PRINT_METHOD("movePrevCandPage");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_movePrevCandPage
  (env, cls, handle);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    aca
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_aca
  (JNIEnv *env, jclass cls, jlong handle){
	PRINT_METHOD("moveNextCandPage");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_moveNextCandPage
  (env, cls, handle);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    acb
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_acb
  (JNIEnv *env, jclass cls, jlong handle, jint idx){
	PRINT_METHOD("getCandInPageByIdx");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_getCandInPageByIdx
  (env, cls, handle, idx);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    acc
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_acc
  (JNIEnv *env, jclass cls, jlong handle, jint idx){
	PRINT_METHOD("getCandInputLenInPageByIdx");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_getCandInputLenInPageByIdx
  (env, cls, handle, idx);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    acd
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_acd
  (JNIEnv *env, jclass cls, jlong handle, jint idx){
	PRINT_METHOD("selectCandInPageByIdx");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_selectCandInPageByIdx
  (env, cls, handle, idx);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    ada
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_ada
  (JNIEnv *env, jclass cls, jlong handle){
	PRINT_METHOD("hasSyllable");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_hasSyllable
  (env, cls, handle);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    adb
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_adb
  (JNIEnv *env, jclass cls, jlong handle){
	PRINT_METHOD("getSyllCountInPage");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_getSyllCountInPage
  (env, cls, handle);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    adc
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_adc
  (JNIEnv *env, jclass cls, jlong handle){
	PRINT_METHOD("hasPrevSyllPage");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_hasPrevSyllPage
  (env, cls, handle);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    add
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_add
  (JNIEnv *env, jclass cls, jlong handle){
	PRINT_METHOD("hasNextSyllPage");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_hasNextSyllPage
  (env, cls, handle);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    baa
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_baa
  (JNIEnv *env, jclass cls, jlong handle){
	PRINT_METHOD("movePrevSyllPage");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_movePrevSyllPage
  (env, cls, handle);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bab
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bab
  (JNIEnv *env, jclass cls, jlong handle){
	PRINT_METHOD("moveNextSyllPage");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_moveNextSyllPage
  (env, cls, handle);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bac
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bac
  (JNIEnv *env, jclass cls, jlong handle, jint idx){
	PRINT_METHOD("getSyllInPageByIdx");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_getSyllInPageByIdx
  (env, cls, handle, idx);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bad
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bad
  (JNIEnv *env, jclass cls, jlong handle, jint idx){
	PRINT_METHOD("selectSyllInPageByIdx");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_selectSyllInPageByIdx
  (env, cls, handle, idx);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bba
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bba
  (JNIEnv *env, jclass cls, jlong handle){
	PRINT_METHOD("getSelectedSyllIdx");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_getSelectedSyllIdx
  (env, cls, handle);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bbb
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bbb
  (JNIEnv *env, jclass cls, jlong handle){
	PRINT_METHOD("getInputString");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_getInputString
  (env, cls, handle);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bbc
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bbc
  (JNIEnv *env, jclass cls, jlong handle){
	PRINT_METHOD("getOutputString");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_getOutputString
  (env, cls, handle);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bbd
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bbd
  (JNIEnv *env, jclass cls, jlong handle){
	PRINT_METHOD("getUpScreenString");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_getUpScreenString
  (env, cls, handle);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bca
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bca
  (JNIEnv *env, jclass cls, jlong handle){
	PRINT_METHOD("clearUpScreenString");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_clearUpScreenString
  (env, cls, handle);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bcb
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bcb
  (JNIEnv *env, jclass cls, jlong handle){
	PRINT_METHOD("getStorkeString");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_getStorkeString
  (env, cls, handle);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bcc
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bcc
  (JNIEnv *env, jclass cls, jlong handle){
	PRINT_METHOD("getComponentsCount");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_getComponentsCount
  (env, cls, handle);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bcd
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bcd
  (JNIEnv *env, jclass cls, jlong handle, jint idx){
	PRINT_METHOD("getComponentStringByIdx");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_getComponentStringByIdx
  (env, cls, handle, idx);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bda
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bda
  (JNIEnv *env, jclass cls, jlong handle, jint idx){
	PRINT_METHOD("getComponentUnicodeByIdx");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_getComponentUnicodeByIdx
  (env, cls, handle, idx);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bdb
 * Signature: (JLjava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bdb
  (JNIEnv *env, jclass cls, jlong handle, jstring str, jboolean reset){
	PRINT_METHOD("setAssocWord");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_setAssocWord
  (env, cls, handle, str, reset);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bdc
 * Signature: (JIIZ)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bdc
  (JNIEnv *env, jclass cls, jlong handle, jint shift_down, jint capslock_toggle, jboolean bUpdateCandidates){
	PRINT_METHOD("setCapState");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_setCapState
  (env, cls, handle, shift_down, capslock_toggle, bUpdateCandidates);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bdd
 * Signature: (JJZ)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bdd
  (JNIEnv *env, jclass cls, jlong handle, jlong config, jboolean on){
	PRINT_METHOD("setFuzzyOptions");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_setFuzzyOptions
  (env, cls, handle, config, on);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    caa
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_caa
  (JNIEnv *env, jclass cls, jlong handle, jint input_mode){
	PRINT_METHOD("switchToSlaveLang");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_switchToSlaveLang
  (env, cls, handle, input_mode);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    cab
 * Signature: (JIJJ)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_cab
  (JNIEnv *env, jclass cls, jlong handle, jint engine_id, jlong config, jlong option){
	PRINT_METHOD("setEngineOption");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_setEngineOption
  (env, cls, handle, engine_id, config, option);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    cac
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_cac
  (JNIEnv *env, jclass cls, jlong handle){
	PRINT_METHOD("getCurState");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_getCurState
  (env, cls, handle);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    cad
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_cad
  (JNIEnv *env, jclass cls, jlong handle, jboolean enable){
	PRINT_METHOD("enableLog");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_enableLog
  (env, cls, handle, enable);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    cba
 * Signature: (JILjava/lang/String;IIIII)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_cba
  (	JNIEnv *env, jclass cls, jlong handle, jint key, jstring str, jint cSplit, jint nCandListType, jint nCandDesireRow, jint nCandCountPerRow, jint nOption ){
	PRINT_METHOD("registerInterpunctionKeyEx");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_registerInterpunctionKeyEx
  (	env, cls, handle, key, str, cSplit, nCandListType, nCandDesireRow, nCandCountPerRow, nOption );

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    cbb
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_cbb
  (JNIEnv *env, jclass cls, jlong handle, jstring cand, jint input_len){
	PRINT_METHOD("selectCandEx");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_selectCandEx
  (env, cls, handle, cand, input_len);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    cbc
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_cbc
  (JNIEnv *env, jclass cls, jlong handle, jstring word, jstring syll){
	PRINT_METHOD("addUDBPhrase");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_addUDBPhrase
  (env, cls, handle, word, syll);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    cbd
 * Signature: (JLjava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_cbd
  (JNIEnv *env, jclass cls, jlong handle, jstring word, jint idx){
	PRINT_METHOD("getPinyinCode");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_getPinyinCode
  (env, cls, handle, word, idx);

}
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    cca
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_cca
  (JNIEnv *env, jclass cls, jlong handle){
	PRINT_METHOD("rewindCandPage");
	return  Java_com_guobi_gbime_engine_GBIMEEngineV52_rewindCandPage
  (env, cls, handle);

}


