/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_guobi_gbime_engine_GBIMEEngineV52 */

#ifndef _Included_com_guobi_gbime_engine_GBIMEEngineV52
#define _Included_com_guobi_gbime_engine_GBIMEEngineV52
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    a
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_a
  (JNIEnv *, jclass);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    b
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_b
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    c
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_c
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    d
 * Signature: (J[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_d
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    aa
 * Signature: (J[B[BI)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_aa
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    ab
 * Signature: (J[B[BI[B[BI)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_ab
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    ac
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_ac
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    ad
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_ad
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    ba
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_ba
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bb
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bb
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bc
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bc
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bd
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bd
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    ca
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_ca
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    cb
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_cb
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    cc
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_cc
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    cd
 * Signature: (JIII)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_cd
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    da
 * Signature: (JIII)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_da
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    db
 * Signature: (JIII)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_db
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    dc
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_dc
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    dd
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_dd
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    aaa
 * Signature: (JIJ)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_aaa
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    aab
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_aab
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    aac
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_aac
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    aad
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_aad
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    aba
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_aba
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    abb
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_abb
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    abc
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_abc
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    abd
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_abd
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    aca
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_aca
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    acb
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_acb
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    acc
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_acc
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    acd
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_acd
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    ada
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_ada
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    adb
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_adb
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    adc
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_adc
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    add
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_add
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    baa
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_baa
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bab
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bab
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bac
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bac
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bad
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bad
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bba
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bba
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bbb
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bbb
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bbc
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bbc
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bbd
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bbd
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bca
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bca
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bcb
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bcb
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bcc
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bcc
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bcd
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bcd
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bda
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bda
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bdb
 * Signature: (JLjava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bdb
  (JNIEnv *, jclass, jlong, jstring, jboolean);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bdc
 * Signature: (JIIZ)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bdc
  (JNIEnv *, jclass, jlong, jint, jint, jboolean);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    bdd
 * Signature: (JJZ)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_bdd
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    caa
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_caa
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    cab
 * Signature: (JIJJ)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_cab
  (JNIEnv *, jclass, jlong, jint, jlong, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    cac
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_cac
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    cad
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_cad
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    cba
 * Signature: (JILjava/lang/String;IIIII)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_cba
  (JNIEnv *, jclass, jlong, jint, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    cbb
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_cbb
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    cbc
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_cbc
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    cbd
 * Signature: (JLjava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_cbd
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     com_guobi_gbime_engine_GBIMEEngineV52
 * Method:    cca
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_guobi_gbime_engine_GBIMEEngineV52_cca
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
